### ISSUE TITLE
Unsound From<&'a mut [T]> implementation

### ISSUE THREAD

**Issue by Plecra** [auxoncorp/fixed-slice-vec#10]
[As mentioned on reddit:](https://www.reddit.com/r/rust/comments/jj537w/fixedslicevec_an_embedded_rust_nostd_vector/gab7m7i/?utm_source=share&utm_medium=web2x&context=3)
> 1. Create an array of 3 `String`.
> 2. Initialize a `FixedSliceVec<'_, String>` with it.
> 3. Call `clear`, all 3 `String` are dropped.
> 4. At the end of the function, the array is dropped, dropping the `String` *again*.

**Comment by Plecra** [comment]
I don't believe it is possible to implement this API, since the referent of a `&mut` must always be valid.

Alternatively, another type could be added specifically designed for `&mut [T]`s using `tinyvec`'s `Default` strategy.

**Comment by ZackPierce** [comment]
Thanks, @Plecra .  That's correct. As noted, that API as written is unsound, and has been removed in https://github.com/auxoncorp/fixed-slice-vec/pull/11 . It is no longer present in fixed-slice-vec 0.6 and up.

I'll look into whether any of the alternatives are suitable in the future.
